import assert from 'node:assert/strict';
import {metrics,matches,STATES,normalizeUE,ueOptions,UNASSIGNED_UE,recordUEs} from './bim-state.js';
const r={start:'2026-09-01',end:'2026-09-30',actual:0};
assert.equal(metrics(r,'2026-08-31').status,'pending');
assert.equal(metrics(r,'2026-09-16').status,'late');
assert.equal(metrics({...r,actual:80},'2026-09-16').status,'started');
assert.equal(metrics({...r,actual:100},'2026-10-01').status,'done');
assert.equal(metrics(r,'2026-10-01').planned,100);
assert.equal(metrics(r,'2026-08-01').planned,0);
assert.equal(STATES.pending.opacity,.12);
const record={section:'E16',discipline:'EST',status:'late',source:'L1T1-1100-316.ifc'};
assert.ok(matches(record,{sector:'E16',discipline:'EST',status:'late',search:'1100'}));
assert.ok(!matches(record,{sector:'E15'}));
assert.ok(!matches(record,{status:'done'}));
console.log('10 assertions passed: schedule boundaries, priority, filters and transparency');
const ueRecords=[{...record,ue:'UE-TEST-1',actual:25},{...record,ue:'UE-TEST-2',actual:75},{...record,ue:null,actual:0}];
assert.equal(ueRecords.filter(r=>matches(r,{ue:'UE-TEST-1'})).length,1);
assert.equal(ueRecords.filter(r=>matches(r,{ue:'UE-TEST-1'}))[0].actual,25);
assert.equal(ueRecords.filter(r=>matches(r,{ue:UNASSIGNED_UE})).length,1);
assert.equal(ueRecords.filter(r=>matches(r,{ue:''})).length,3);
assert.equal(ueRecords.filter(r=>matches(r,{ue:'UE-TEST-1',sector:'E15'})).length,0);
assert.equal(ueRecords.filter(r=>matches(r,{ue:'UE-TEST-1',sector:'E16',discipline:'EST',status:'late'})).length,1);
assert.deepEqual(ueOptions([...ueRecords,{ue:' UE-TEST-1 '}]),['UE-TEST-1','UE-TEST-2']);
assert.equal(normalizeUE(null),'');
assert.equal(normalizeUE(['UE-TEST-1','UE-TEST-2']),'');
console.log('9 UE assertions passed: independent units, combined filters, reset and missing mapping');
const shared=[{...record,section:'I16',ues:['93'],count:99},{...record,section:'E16',ues:['093'],count:6},{...record,section:'E16',ues:['93','94'],count:55},{...record,ues:['N/A'],count:30}];
assert.equal(shared.filter(r=>matches(r,{ue:'93'})).reduce((n,r)=>n+r.count,0),160);
assert.equal(shared.filter(r=>matches(r,{ue:'93',sector:'E16'})).reduce((n,r)=>n+r.count,0),61);
assert.equal(shared.filter(r=>matches(r,{ue:'94'})).length,1);
assert.deepEqual(recordUEs({ues:['93','093','N/A']}),['93']);
assert.equal(shared.filter(r=>matches(r,{ue:UNASSIGNED_UE})).length,1);
assert.deepEqual(ueOptions(shared),['93','94']);
console.log('6 many-to-many assertions passed: shared UE, multi-membership, zero padding, missing values');
