const $=id=>document.getElementById(id);
let pdfDoc=null,pdfTask=null;
let documents=[],selected=null,version=0,workbook=null,page=0,rows=[],localUrl=null;
const PAGE=100;
const kind=ext=>({pdf:'PDF',docx:'Word',xls:'Excel',xlsx:'Excel',csv:'Excel',jpg:'Imagen',jpeg:'Imagen',png:'Imagen',webp:'Imagen',gif:'Imagen',mp4:'Video',webm:'Video',mp3:'Audio',wav:'Audio',m4a:'Audio',ogg:'Audio'}[ext.toLowerCase()]||'Otro');
const bytes=n=>n?`${(n/1024/1024).toLocaleString('es',{maximumFractionDigits:1})} MB`:'';
const text=(tag,value,cls)=>{const e=document.createElement(tag);e.textContent=value;if(cls)e.className=cls;return e;};
function notice(message){$('notice').hidden=!message;$('notice').textContent=message||'';}
function renderCatalog(){
 const search=$('search').value.toLocaleLowerCase('es'),type=$('type').value,sector=$('sector').value;
 const filtered=documents.filter(d=>(!type||d.type===type)&&(!sector||d.sector===sector)&&`${d.name} ${d.description||''}`.toLocaleLowerCase('es').includes(search));
 $('count').textContent=`${filtered.length} de ${documents.length} archivos`;$('catalog').replaceChildren();
 for(const d of filtered){const b=document.createElement('button');b.className='docCard';b.setAttribute('aria-pressed',String(selected?.id===d.id));b.append(text('span',`${d.type} · ${d.sector||'Proyecto'}`),text('b',d.name),text('small',d.webVersion?'Video completo · versión web':bytes(d.bytes)));b.onclick=()=>openDocument(d);$('catalog').append(b);}
 if(!filtered.length)$('catalog').append(text('p','No hay documentos que coincidan con los filtros.','muted'));
}
function clearViewer(){if(pdfTask){pdfTask.cancel();pdfTask=null;}if(pdfDoc){pdfDoc.destroy();pdfDoc=null;}const media=$('viewer').querySelector('video,audio');if(media){media.pause();media.removeAttribute('src');media.load();}$('viewer').replaceChildren();$('tools').hidden=true;notice('');}
function message(value,link,label){const box=text('div',value,'message');if(link){const a=text('a',label||'Abrir');a.href=link;a.target='_blank';a.rel='noopener noreferrer';box.append(document.createElement('br'),a);}$('viewer').replaceChildren(box);}
async function readBuffer(d){if(d.file)return d.file.arrayBuffer();const r=await fetch(d.url);if(!r.ok)throw Error('El archivo no está disponible.');return r.arrayBuffer();}
async function waitLibrary(name){for(let i=0;i<100;i++){if(window[name])return window[name];await new Promise(r=>setTimeout(r,100));}throw Error('No se pudo cargar el lector. Recarga la página.');}
async function openDocument(d){
 const current=++version;selected=d;workbook=null;clearViewer();renderCatalog();$('docType').textContent=`${d.type} · ${d.sector||'Proyecto'}${d.file?' · Solo esta sesión':''}`;$('docName').textContent=d.name;$('docDescription').textContent=d.description||'';
 $('download').hidden=!d.url;if(d.url){$('download').href=d.url;$('download').download=d.webVersion?'obra-e15-20260831-web.mp4':d.name;$('download').textContent=d.webVersion?'Descargar versión web':'Descargar original';}
 try{
 if(d.type==='Power BI'){message('El formato PBIX requiere Power BI Desktop. Para visualizar el informe interactivo, abre Power BI. El acceso depende de los permisos del informe.',d.reportUrl,'Abrir informe de Power BI');return;}
 if(d.type==='PDF'){
 message('Preparando PDF…');const [P,buffer]=await Promise.all([import('./vendor/pdf-4.10.38.min.js'),readBuffer(d)]);if(current!==version)return;
 P.GlobalWorkerOptions.workerSrc=new URL('./vendor/pdf.worker-4.10.38.min.js',location.href).href;
 const pdf=await P.getDocument({data:new Uint8Array(buffer),isEvalSupported:false}).promise;if(current!==version){pdf.destroy();return;}pdfDoc=pdf;
 const shell=document.createElement('div');shell.className='pdfShell';const bar=document.createElement('div');bar.className='pdfBar';const prev=text('button','Página anterior'),next=text('button','Página siguiente'),info=text('span',''),minus=text('button','−'),plus=text('button','+');minus.setAttribute('aria-label','Reducir PDF');plus.setAttribute('aria-label','Ampliar PDF');bar.append(prev,info,next,minus,plus);const canvas=document.createElement('canvas');canvas.setAttribute('aria-label','Página del PDF');shell.append(bar,canvas);$('viewer').replaceChildren(shell);let number=1,zoom=1,renderId=0;
 async function draw(){const job=++renderId;try{if(pdfTask){pdfTask.cancel();await pdfTask.promise.catch(()=>{});pdfTask=null;}const page=await pdf.getPage(number);if(current!==version||job!==renderId)return;const base=page.getViewport({scale:1}),scale=Math.max(200,$('viewer').clientWidth-36)/base.width*zoom,view=page.getViewport({scale}),ratio=Math.min(devicePixelRatio||1,2);canvas.width=Math.floor(view.width*ratio);canvas.height=Math.floor(view.height*ratio);canvas.style.width=view.width+'px';canvas.style.height=view.height+'px';info.textContent=`Página ${number} de ${pdf.numPages}`;canvas.setAttribute('aria-label',info.textContent);prev.disabled=number===1;next.disabled=number===pdf.numPages;minus.disabled=zoom<=.5;plus.disabled=zoom>=2;pdfTask=page.render({canvasContext:canvas.getContext('2d'),viewport:view,transform:ratio===1?null:[ratio,0,0,ratio,0,0]});await pdfTask.promise;}catch(e){if(e.name!=='RenderingCancelledException'&&current===version)notice('No se pudo representar esta página. Puedes descargar el PDF original.');}}
 prev.onclick=()=>{number--;draw();};next.onclick=()=>{number++;draw();};minus.onclick=()=>{zoom=Math.max(.5,zoom-.25);draw();};plus.onclick=()=>{zoom=Math.min(2,zoom+.25);draw();};await draw();return;
 }
 if(d.type==='Imagen'){const img=document.createElement('img');img.alt=d.name;img.src=d.url;img.onerror=()=>{if(current===version)message('No se pudo cargar la imagen. Usa la descarga para comprobar el archivo.');};$('viewer').append(img);return;}
 if(d.type==='Video'||d.type==='Audio'){const media=document.createElement(d.type==='Video'?'video':'audio');media.controls=true;media.preload='metadata';media.src=d.url;if(d.type==='Video')media.playsInline=true;media.onerror=()=>{if(current===version)notice('El navegador no puede reproducir este archivo. Descárgalo para abrirlo con otro reproductor.');};$('viewer').append(media);return;}
 if(d.type==='Excel'||d.type==='Word'){
 if(d.file?.size>30*1024*1024)throw Error('Para archivos de más de 30 MB utiliza la descarga y la aplicación de escritorio.');
 message('Preparando vista de lectura…');const buffer=await readBuffer(d);if(current!==version)return;
 if(d.type==='Excel'){const X=await waitLibrary('XLSX');if(current!==version)return;workbook=X.read(buffer,{type:'array',cellDates:true});$('sheet').replaceChildren(...workbook.SheetNames.map(n=>{const o=text('option',n);o.value=n;return o;}));$('tools').hidden=false;notice('Vista de datos guardados. Las fórmulas no se recalculan; los gráficos y el diseño completo se consultan en el original.');showSheet();return;}
 const M=await waitLibrary('mammoth');const result=await M.convertToHtml({arrayBuffer:buffer});if(current!==version)return;
 const parsed=new DOMParser().parseFromString(result.value,'text/html');const allowed=new Set(['P','H1','H2','H3','H4','H5','H6','TABLE','THEAD','TBODY','TR','TD','TH','STRONG','B','EM','I','U','S','UL','OL','LI','BR','BLOCKQUOTE','PRE','CODE','IMG']);
 function clean(node){if(node.nodeType===3)return document.createTextNode(node.textContent);if(node.nodeType!==1)return document.createTextNode('');if(['SCRIPT','STYLE','IFRAME','OBJECT','SVG'].includes(node.tagName))return document.createTextNode('');const out=document.createElement(allowed.has(node.tagName)?node.tagName:'span');if(node.tagName==='IMG'){const src=node.getAttribute('src')||'';if(/^data:image\/(png|jpeg|gif|webp);base64,/i.test(src))out.setAttribute('src',src);out.setAttribute('alt',node.getAttribute('alt')||'Imagen del documento');}if(['TD','TH'].includes(node.tagName))for(const k of ['colspan','rowspan']){const v=Number(node.getAttribute(k));if(v>0&&v<100)out.setAttribute(k,String(v));}for(const child of node.childNodes)out.append(clean(child));return out;}
 const body=document.createElement('div');for(const child of parsed.body.childNodes)body.append(clean(child));const frame=document.createElement('iframe');frame.title=d.name;frame.setAttribute('sandbox','');frame.srcdoc=`<!doctype html><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'"><style>body{font:16px/1.6 Arial;color:#172531;padding:30px;max-width:900px;margin:auto}img{max-width:100%}table{border-collapse:collapse}td,th{border:1px solid #aaa;padding:8px}h1,h2,h3{color:#24485e}</style>${body.innerHTML}`;$('viewer').replaceChildren(frame);notice('Vista de lectura de Word. El diseño puede diferir del documento original.');return;
 }
 message('Este formato no tiene vista previa. Descarga el archivo para abrirlo con su aplicación.');
 }catch(e){if(current===version){message(e.message||'No se pudo abrir el documento.');$('viewer').firstChild?.classList.add('error');}}
}
function showSheet(){if(!workbook)return;const X=window.XLSX;rows=X.utils.sheet_to_json(workbook.Sheets[$('sheet').value],{header:1,raw:false,defval:'',blankrows:true});page=0;renderSheet();}
function renderSheet(){const X=window.XLSX;const total=rows.length,columns=Math.max(1,...rows.map(r=>r.length));const table=document.createElement('table'),head=document.createElement('thead'),tr=document.createElement('tr');tr.append(text('th','Fila'));for(let c=0;c<columns;c++)tr.append(text('th',X.utils.encode_col(c)));head.append(tr);table.append(head);const body=document.createElement('tbody');for(let i=page*PAGE;i<Math.min(total,(page+1)*PAGE);i++){const r=document.createElement('tr');r.append(text('th',String(i+1)));for(let c=0;c<columns;c++)r.append(text('td',String(rows[i][c]??'')));body.append(r);}table.append(body);$('viewer').replaceChildren(table);$('viewer').scrollTop=0;$('pageInfo').textContent=total?`Filas ${page*PAGE+1}–${Math.min(total,(page+1)*PAGE)} de ${total}`:'Hoja vacía';$('previous').disabled=page===0;$('next').disabled=(page+1)*PAGE>=total;}
$('search').oninput=renderCatalog;$('type').onchange=renderCatalog;$('sector').onchange=renderCatalog;$('reset').onclick=()=>{for(const id of ['search','type','sector'])$(id).value='';renderCatalog();};$('sheet').onchange=showSheet;$('previous').onclick=()=>{page--;renderSheet();};$('next').onclick=()=>{page++;renderSheet();};
$('local').onchange=e=>{const file=e.target.files[0];if(!file)return;if(localUrl)URL.revokeObjectURL(localUrl);localUrl=URL.createObjectURL(file);openDocument({id:'local',name:file.name,type:kind(file.name.split('.').pop()),file,url:localUrl,description:'Archivo local. No se envía ni se añade al catálogo público.'});};
async function init(){try{const r=await fetch('documents.json');if(!r.ok)throw Error('No se pudo cargar el catálogo.');documents=(await r.json()).documents;const query=new URLSearchParams(location.search);if(['E15','I16','E16'].includes(query.get('sector')))$('sector').value=query.get('sector');renderCatalog();const requested=documents.find(d=>d.id===query.get('document'));if(requested)openDocument(requested);}catch(e){$('count').textContent=e.message;}}
init();
