const $=id=>document.getElementById(id);
let pdfDoc=null,pdfTask=null,pdfLoadingTask=null;
let documents=[],selected=null,version=0,workbook=null,page=0,rows=[],localUrl=null,activeChipFilter='';
const PAGE=100;
const UNAVAILABLE_DOCUMENT_HOSTS=new Set(['almacenamientoemb.blob.core.windows.net']);
const PREDIAL_LINK_SESSION_KEY='gd-predial-document-links-v1';
const queryParams=new URLSearchParams(location.search);
if(queryParams.get('embed')==='1')document.body.classList.add('embedMode');
async function loadGzipJSON(url){const response=await fetch(url);if(!response.ok)throw new Error(`No se pudo cargar ${url}`);const stream=response.body.pipeThrough(new DecompressionStream('gzip'));return JSON.parse(await new Response(stream).text());}
const normalizeChip=value=>String(value||'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const kind=ext=>({pdf:'PDF',docx:'Word',xls:'Excel',xlsx:'Excel',csv:'Excel',jpg:'Imagen',jpeg:'Imagen',png:'Imagen',webp:'Imagen',gif:'Imagen',mp4:'Video',webm:'Video',mp3:'Audio',wav:'Audio',m4a:'Audio',ogg:'Audio',zip:'Archivo comprimido'}[ext.toLowerCase()]||'Otro');
const viewType=d=>d.type==='Documento predial'?kind(d.name.split('.').pop()):d.type;
const bytes=n=>n?`${(n/1024/1024).toLocaleString('es',{maximumFractionDigits:1})} MB`:'';
const text=(tag,value,cls)=>{const e=document.createElement(tag);e.textContent=value;if(cls)e.className=cls;return e;};
function notice(message){$('notice').hidden=!message;$('notice').textContent=message||'';}
function renderCatalog(){
 const search=$('search').value.toLocaleLowerCase('es'),type=$('type').value,sector=$('sector').value;
 const filtered=documents.filter(d=>(!activeChipFilter||d.chip===activeChipFilter)&&(!type||d.type===type)&&(!sector||d.sector===sector)&&`${d.name} ${d.description||''} ${d.chip||''} ${d.lotCode||''} ${d.parcelId||''} ${d.address||''}`.toLocaleLowerCase('es').includes(search));
 $('count').textContent=`${filtered.length} de ${documents.length} archivos`;$('catalog').replaceChildren();
 for(const d of filtered){const b=document.createElement('button');b.className='docCard';b.setAttribute('aria-pressed',String(selected?.id===d.id));const linkState=d.linkUnavailable?'no disponible en origen':d.url?'habilitado':'requiere Excel',detail=d.type==='Documento predial'?`CHIP ${d.chip||'sin dato'}${d.parcelId?` · ${d.parcelId}`:''} · ${linkState}`:(d.webVersion?'Video completo · versión web':bytes(d.bytes));b.append(text('span',`${d.type} · ${d.sector||'Proyecto'}`),text('b',d.name),text('small',detail));b.onclick=()=>openDocument(d);$('catalog').append(b);}
 if(!filtered.length)$('catalog').append(text('p','No hay documentos que coincidan con los filtros.','muted'));
}
function clearViewer(){if(pdfTask){pdfTask.cancel();pdfTask=null;}if(pdfLoadingTask){pdfLoadingTask.destroy();pdfLoadingTask=null;}if(pdfDoc){pdfDoc.destroy();pdfDoc=null;}const media=$('viewer').querySelector('video,audio');if(media){media.pause();media.removeAttribute('src');media.load();}$('viewer').replaceChildren();$('tools').hidden=true;notice('');}
function message(value,link,label){const box=text('div',value,'message');if(link){const a=text('a',label||'Abrir');a.href=link;a.target='_blank';a.rel='noopener noreferrer';box.append(document.createElement('br'),a);}$('viewer').replaceChildren(box);}
function predialMessage(d){const type=viewType(d),state=d.linkUnavailable?'El vínculo existe en el catálogo, pero su contenedor de origen no está disponible.':!d.url?'Selecciona el Excel de vínculos para habilitar la vista integrada sin publicar el token.':type==='Archivo comprimido'?'Este registro es un archivo ZIP y no tiene representación visual directa. Los 906 documentos PDF restantes se abren dentro del mockup.':'Este formato no tiene una vista integrada disponible.';const box=text('div',state,'message predialMessage');const meta=text('p',`CHIP: ${d.chip||'Sin dato'}${d.lotCode?` · LotCodigo: ${d.lotCode}`:''}${d.address?` · ${d.address}`:''}`,'predialMeta');box.append(meta);const actions=document.createElement('div');actions.className='documentActions';if(d.chip&&queryParams.get('embed')!=='1'){const map=text('a','Ver predio en el mapa');map.href=`./predial.html?chip=${encodeURIComponent(d.chip)}`;actions.append(map);}box.append(actions);$('viewer').replaceChildren(box);}
function persistPredialLinks(list){const links=list.filter(d=>d.type==='Documento predial'&&d.url).map(d=>({id:d.id,chip:d.chip,url:d.url,unavailable:Boolean(d.linkUnavailable)}));sessionStorage.setItem(PREDIAL_LINK_SESSION_KEY,JSON.stringify({loadedAt:Date.now(),links}));}
function restorePredialLinks(list){try{const saved=JSON.parse(sessionStorage.getItem(PREDIAL_LINK_SESSION_KEY)||'{}'),byId=new Map(list.filter(d=>d.type==='Documento predial').map(d=>[d.id,d]));for(const item of saved.links||[]){const document=byId.get(item.id),link=tokenUrl(item.url);if(document&&link.url&&document.chip===normalizeChip(item.chip)){document.url=link.url;document.linkUnavailable=Boolean(item.unavailable||link.unavailable);}}}catch{sessionStorage.removeItem(PREDIAL_LINK_SESSION_KEY);}}
async function readBuffer(d){if(d.file)return d.file.arrayBuffer();const r=await fetch(d.url);if(!r.ok)throw Error('El archivo no está disponible.');return r.arrayBuffer();}
async function waitLibrary(name){for(let i=0;i<100;i++){if(window[name])return window[name];await new Promise(r=>setTimeout(r,100));}throw Error('No se pudo cargar el lector. Recarga la página.');}
async function enablePredialLinks(file){const status=$('predialLinkStatus');status.textContent='Leyendo vínculos en este navegador…';try{const X=await waitLibrary('XLSX'),workbook=X.read(await file.arrayBuffer(),{type:'array',cellDates:true}),sheet=workbook.Sheets['Documentos_Identificacion_Predi'];if(!sheet)throw Error('No se encontró la hoja Documentos_Identificacion_Predi.');const rows=X.utils.sheet_to_json(sheet,{header:1,raw:false,defval:''}),headers=rows[0].map(value=>String(value).trim()),positions=Object.fromEntries(headers.map((name,index)=>[name,index]));for(const required of ['Documentos_Identificacion_PredioId','enlace_web_token','chip'])if(!(required in positions))throw Error(`Falta la columna ${required}.`);const byId=new Map(documents.filter(document=>document.type==='Documento predial').map(document=>[document.id,document]));let enabled=0,unavailable=0;rows.slice(1).forEach((row,index)=>{const rowNo=index+2,sourceId=String(row[positions.Documentos_Identificacion_PredioId]||'').trim(),id=`predial-doc-${sourceId||rowNo}-${rowNo}`,document=byId.get(id),link=tokenUrl(row[positions.enlace_web_token]),chip=normalizeChip(row[positions.chip]);if(document&&link.url&&document.chip===chip){document.url=link.url;document.linkUnavailable=link.unavailable;if(link.unavailable)unavailable++;else enabled++;}});persistPredialLinks(documents);status.textContent=`${enabled.toLocaleString('es-CO')} vínculos disponibles en el visor integrado; ${unavailable.toLocaleString('es-CO')} no disponibles en el origen.`;renderCatalog();if(selected?.type==='Documento predial')openDocument(selected);}catch(error){status.textContent=error.message||'No se pudieron habilitar los vínculos.';}}
const tokenUrl=value=>{try{const url=new URL(String(value||'')),host=url.hostname.toLowerCase();if(url.protocol!=='https:'||!host.endsWith('.blob.core.windows.net'))return{url:'',unavailable:false};return{url:url.href,unavailable:UNAVAILABLE_DOCUMENT_HOSTS.has(host)};}catch{return{url:'',unavailable:false};}};
async function openDocument(d){
 const current=++version,type=viewType(d);selected=d;workbook=null;clearViewer();renderCatalog();$('docType').textContent=`${d.type}${type!==d.type?` · ${type}`:''} · ${d.sector||'Proyecto'}${d.file?' · Solo esta sesión':''}`;$('docName').textContent=d.name;$('docDescription').textContent=d.description||'';
 const download=$('download');download.hidden=d.type==='Documento predial'||!d.url||Boolean(d.linkUnavailable);download.onclick=null;download.removeAttribute('role');if(d.type!=='Documento predial'&&d.url){download.href=d.url;download.download=d.webVersion?'obra-e15-20260831-web.mp4':d.name;download.target='';download.rel='';download.textContent=d.webVersion?'Descargar versión web':'Descargar original';}
 try{
 if(d.type==='Documento predial'&&(!d.url||d.linkUnavailable||type!=='PDF')){predialMessage(d);return;}
 if(type==='Power BI'){message('El formato PBIX requiere Power BI Desktop. Para visualizar el informe interactivo, abre Power BI. El acceso depende de los permisos del informe.',d.reportUrl,'Abrir informe de Power BI');return;}
 if(type==='PDF'){
 message(d.type==='Documento predial'?'Preparando vista PDF por bloques…':'Preparando PDF…');const P=await import('./vendor/pdf-4.10.38.min.js');if(current!==version)return;
 P.GlobalWorkerOptions.workerSrc=new URL('./vendor/pdf.worker-4.10.38.min.js',location.href).href;
 let source;if(d.type==='Documento predial')source={url:d.url,rangeChunkSize:131072,disableAutoFetch:true,isEvalSupported:false};else{const buffer=await readBuffer(d);if(current!==version)return;source={data:new Uint8Array(buffer),isEvalSupported:false};}
 const loading=P.getDocument(source);pdfLoadingTask=loading;const pdf=await loading.promise;if(pdfLoadingTask===loading)pdfLoadingTask=null;if(current!==version){pdf.destroy();return;}pdfDoc=pdf;
 const shell=document.createElement('div');shell.className='pdfShell';const bar=document.createElement('div');bar.className='pdfBar';const prev=text('button','Página anterior'),next=text('button','Página siguiente'),info=text('span',''),minus=text('button','−'),plus=text('button','+');minus.setAttribute('aria-label','Reducir PDF');plus.setAttribute('aria-label','Ampliar PDF');bar.append(prev,info,next,minus,plus);const canvas=document.createElement('canvas');canvas.setAttribute('aria-label','Página del PDF');shell.append(bar,canvas);$('viewer').replaceChildren(shell);let number=1,zoom=1,renderId=0;
 async function draw(){const job=++renderId;try{if(pdfTask){pdfTask.cancel();await pdfTask.promise.catch(()=>{});pdfTask=null;}const page=await pdf.getPage(number);if(current!==version||job!==renderId)return;const base=page.getViewport({scale:1}),scale=Math.max(200,$('viewer').clientWidth-36)/base.width*zoom,view=page.getViewport({scale}),ratio=Math.min(devicePixelRatio||1,2);canvas.width=Math.floor(view.width*ratio);canvas.height=Math.floor(view.height*ratio);canvas.style.width=view.width+'px';canvas.style.height=view.height+'px';info.textContent=`Página ${number} de ${pdf.numPages}`;canvas.setAttribute('aria-label',info.textContent);prev.disabled=number===1;next.disabled=number===pdf.numPages;minus.disabled=zoom<=.5;plus.disabled=zoom>=2;pdfTask=page.render({canvasContext:canvas.getContext('2d'),viewport:view,transform:ratio===1?null:[ratio,0,0,ratio,0,0]});await pdfTask.promise;}catch(e){if(e.name!=='RenderingCancelledException'&&current===version)notice('No se pudo representar esta página. Puedes descargar el PDF original.');}}
 prev.onclick=()=>{number--;draw();};next.onclick=()=>{number++;draw();};minus.onclick=()=>{zoom=Math.max(.5,zoom-.25);draw();};plus.onclick=()=>{zoom=Math.min(2,zoom+.25);draw();};await draw();return;
 }
 if(type==='Imagen'){const img=document.createElement('img');img.alt=d.name;img.src=d.url;img.onerror=()=>{if(current===version)message('No se pudo cargar la imagen. Usa la descarga para comprobar el archivo.');};$('viewer').append(img);return;}
 if(type==='Video'||type==='Audio'){const media=document.createElement(type==='Video'?'video':'audio');media.controls=true;media.preload='metadata';media.src=d.url;if(type==='Video')media.playsInline=true;media.onerror=()=>{if(current===version)notice('El navegador no puede reproducir este archivo. Descárgalo para abrirlo con otro reproductor.');};$('viewer').append(media);return;}
 if(type==='Excel'||type==='Word'){
 if(d.file?.size>30*1024*1024)throw Error('Para archivos de más de 30 MB utiliza la descarga y la aplicación de escritorio.');
 message('Preparando vista de lectura…');const buffer=await readBuffer(d);if(current!==version)return;
 if(type==='Excel'){const X=await waitLibrary('XLSX');if(current!==version)return;workbook=X.read(buffer,{type:'array',cellDates:true});$('sheet').replaceChildren(...workbook.SheetNames.map(n=>{const o=text('option',n);o.value=n;return o;}));$('tools').hidden=false;notice('Vista de datos guardados. Las fórmulas no se recalculan; los gráficos y el diseño completo se consultan en el original.');showSheet();return;}
 const M=await waitLibrary('mammoth');const result=await M.convertToHtml({arrayBuffer:buffer});if(current!==version)return;
 const parsed=new DOMParser().parseFromString(result.value,'text/html');const allowed=new Set(['P','H1','H2','H3','H4','H5','H6','TABLE','THEAD','TBODY','TR','TD','TH','STRONG','B','EM','I','U','S','UL','OL','LI','BR','BLOCKQUOTE','PRE','CODE','IMG']);
 function clean(node){if(node.nodeType===3)return document.createTextNode(node.textContent);if(node.nodeType!==1)return document.createTextNode('');if(['SCRIPT','STYLE','IFRAME','OBJECT','SVG'].includes(node.tagName))return document.createTextNode('');const out=document.createElement(allowed.has(node.tagName)?node.tagName:'span');if(node.tagName==='IMG'){const src=node.getAttribute('src')||'';if(/^data:image\/(png|jpeg|gif|webp);base64,/i.test(src))out.setAttribute('src',src);out.setAttribute('alt',node.getAttribute('alt')||'Imagen del documento');}if(['TD','TH'].includes(node.tagName))for(const k of ['colspan','rowspan']){const v=Number(node.getAttribute(k));if(v>0&&v<100)out.setAttribute(k,String(v));}for(const child of node.childNodes)out.append(clean(child));return out;}
 const body=document.createElement('div');for(const child of parsed.body.childNodes)body.append(clean(child));const frame=document.createElement('iframe');frame.title=d.name;frame.setAttribute('sandbox','');frame.srcdoc=`<!doctype html><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'"><style>body{font:16px/1.6 Arial;color:#172531;padding:30px;max-width:900px;margin:auto}img{max-width:100%}table{border-collapse:collapse}td,th{border:1px solid #aaa;padding:8px}h1,h2,h3{color:#24485e}</style>${body.innerHTML}`;$('viewer').replaceChildren(frame);notice('Vista de lectura de Word. El diseño puede diferir del documento original.');return;
 }
 message('Este formato no tiene vista previa. Descarga el archivo para abrirlo con su aplicación.');
 }catch(e){if(current===version){message(e.message||'No se pudo abrir el documento.');$('viewer').firstChild?.classList.add('error');}}
}
function showSheet(){if(!workbook)return;const X=window.XLSX;rows=X.utils.sheet_to_json(workbook.Sheets[$('sheet').value],{header:1,raw:false,defval:'',blankrows:true});page=0;renderSheet();}
function renderSheet(){const X=window.XLSX;const total=rows.length,columns=Math.max(1,...rows.map(r=>r.length));const table=document.createElement('table'),head=document.createElement('thead'),tr=document.createElement('tr');tr.append(text('th','Fila'));for(let c=0;c<columns;c++)tr.append(text('th',X.utils.encode_col(c)));head.append(tr);table.append(head);const body=document.createElement('tbody');for(let i=page*PAGE;i<Math.min(total,(page+1)*PAGE);i++){const r=document.createElement('tr');r.append(text('th',String(i+1)));for(let c=0;c<columns;c++)r.append(text('td',String(rows[i][c]??'')));body.append(r);}table.append(body);$('viewer').replaceChildren(table);$('viewer').scrollTop=0;$('pageInfo').textContent=total?`Filas ${page*PAGE+1}–${Math.min(total,(page+1)*PAGE)} de ${total}`:'Hoja vacía';$('previous').disabled=page===0;$('next').disabled=(page+1)*PAGE>=total;}
$('search').oninput=()=>{activeChipFilter='';renderCatalog();};$('type').onchange=renderCatalog;$('sector').onchange=renderCatalog;$('reset').onclick=()=>{activeChipFilter='';for(const id of ['search','type','sector'])$(id).value='';renderCatalog();};$('sheet').onchange=showSheet;$('previous').onclick=()=>{page--;renderSheet();};$('next').onclick=()=>{page++;renderSheet();};
$('predialLinks').onchange=event=>{const file=event.target.files?.[0];if(file)enablePredialLinks(file);};
$('local').onchange=e=>{const file=e.target.files[0];if(!file)return;if(localUrl)URL.revokeObjectURL(localUrl);localUrl=URL.createObjectURL(file);openDocument({id:'local',name:file.name,type:kind(file.name.split('.').pop()),file,url:localUrl,description:'Archivo local. No se envía ni se añade al catálogo público.'});};
async function init(){try{const [catalogResponse,predialPayload]=await Promise.all([fetch('documents.json'),loadGzipJSON('./predial-data.json.gz?v=20260928-chip-docs')]);if(!catalogResponse.ok)throw Error('No se pudo cargar el catálogo.');const catalog=await catalogResponse.json(),recordByChip=new Map(predialPayload.records.filter(record=>record.chip).map(record=>[record.chip,record]));const predialDocuments=(predialPayload.documents||[]).map(document=>{const record=recordByChip.get(document.chip);return{...document,type:'Documento predial',sector:'Predial',description:`Documento de identificación predial${document.chip?` · CHIP ${document.chip}`:' · sin CHIP para remapeo'}${record?.id?` · ${record.id}`:''}`,lotCode:record?.lotCode||'',parcelId:record?.id||'',address:record?.address||''};});documents=[...(catalog.documents||[]),...predialDocuments];restorePredialLinks(documents);const sector=queryParams.get('sector'),chip=normalizeChip(queryParams.get('chip'));if(['E15','I16','E16','Predial'].includes(sector))$('sector').value=sector;if(chip){activeChipFilter=chip;$('sector').value='Predial';$('search').value=chip;}renderCatalog();const requested=documents.find(d=>d.id===queryParams.get('document'))||(chip?documents.find(d=>d.chip===chip):null);if(requested)openDocument(requested);}catch(e){$('count').textContent=e.message;}}
init();
