import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import * as THREE from './vendor/three.module.js';
import {stationMenu,stationSimulationContents} from './station-management-ui.js';
import {DEFAULT_FLOW} from './station-flow.js';
const moduleUrl=name=>new URL(name,import.meta.url).href;
const batches=(await fs.readFile(new URL('./ifc-render-batches.js',import.meta.url),'utf8')).replace("from 'three'",`from '${moduleUrl('./vendor/three.module.js')}'`);
const batchUrl='data:text/javascript;base64,'+Buffer.from(batches).toString('base64');
const source=(await fs.readFile(new URL('./station-model-controls.js',import.meta.url),'utf8')).replace("from 'three'",`from '${moduleUrl('./vendor/three.module.js')}'`).replace(/from '\.\/ifc-render-batches\.js[^']*'/,`from '${batchUrl}'`).replace(/from '\.\/station-levels\.js[^']*'/,`from '${moduleUrl('./station-levels.js')}'`);
const {createStationModelControls}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const root=new THREE.Group(),group=new THREE.Group();root.add(group);
const geometry=new THREE.BoxGeometry(6,1.8,8),material=new THREE.MeshStandardMaterial(),mesh=new THREE.Mesh(geometry,material);mesh.position.y=1.2;mesh.userData.progressObject={id:'immutable-ifc-instance'};group.add(mesh);
const before=geometry.attributes.position.array.slice(),bounds=new THREE.Box3(new THREE.Vector3(-3,.24,-4),new THREE.Vector3(3,2.1,4));
const controls=createStationModelControls(root,{group},'E15',bounds),flow=root.getObjectByName('Flujos teóricos · trayectorias esquemáticas');
controls.setFlow({entries:600,exits:900,total:1500},5);assert.equal(flow.visible,true);assert.equal(flow.children[0].count,20);assert.equal(flow.children[1].count,30);
const a=new THREE.Matrix4(),b=new THREE.Matrix4();flow.children[0].getMatrixAt(0,a);
controls.setLevel('all',true);controls.setFlow({entries:600,exits:900,total:1500},5);flow.children[0].getMatrixAt(0,b);assert.ok(Math.abs(b.elements[13]-a.elements[13]-.9)<1e-6);
controls.setLevel('lower',false);controls.setFlow({entries:600,exits:900,total:1500},5);assert.equal(flow.visible,false);
controls.setLevel('upper',false);controls.setFlow(null,5);assert.equal(flow.visible,false);
controls.setFlow({entries:100000,exits:100000,total:200000},5);assert.equal(flow.children[0].count,96);
assert.deepEqual(geometry.attributes.position.array,before);assert.equal(mesh.userData.progressObject.id,'immutable-ifc-instance');
const c1=controls.cameraPose(0);controls.activateCamera(0);const c2=controls.cameraPose(0);assert.equal(c1.position.distanceTo(c2.position),0);
controls.setAlarm(true);assert.equal(root.getObjectByName('Alarma y evacuación simuladas · E15').visible,true);controls.setAlarm(false);
const html=stationSimulationContents(DEFAULT_FLOW);for(const label of ['Hora pico','Hora Valle','Evento','Fin de semana'])assert.ok(html.includes(label));assert.ok(html.includes('SIN DATOS DE AFORO'));assert.ok(stationMenu('levels','Niveles','x').includes('<summary>Niveles'));
controls.dispose();console.log('Station controls: flow follows level separation, hidden levels suppress marks, identities unchanged, fixed camera/alarms preserved, bounded instancing and four scenarios PASS');
